language: android
android:
  components:
    - build-tools-20.0.0
    - android-20
    - sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-20


script: ./gradlew clean build :odata-engine-unit-tests:test --stacktrace